export const descriptionsJson = {
    "descriptions":  {
        Pathfinder: "The Pathfinder is energized by an innate curiosity and a thirst for exploration, thriving on new experiences and uncharted territories. They excel in dynamic and ever-changing environments, where adaptability and discovery are essential. Careers in fields like research, travel, entrepreneurship, or innovation often align with their adventurous spirit. Pathfinders are energized by seeking answers, pushing boundaries, and pursuing growth, both for themselves and others. They flourish in roles that allow them to explore possibilities, embrace novelty, and challenge conventional ways of thinking.",
        Artisan: "The Artisan is a creator at heart, drawn to crafting, building, or shaping things with care and precision. They find joy in hands-on work and take pride in producing tangible, high-quality outcomes. Careers in design, engineering, fine arts, woodworking, culinary arts, or any field requiring detailed craftsmanship are well-suited for Artisans. They thrive in environments where creativity meets practicality, allowing them to immerse themselves in their work and focus on perfecting their craft. Artisans value the satisfaction of seeing their efforts come to life.",
        Loreweaver: "The Loreweaver is a master storyteller, connecting people and ideas through the power of narrative. They excel at capturing attention, conveying emotion, and inspiring others with their words or creations. Careers in writing, filmmaking, public speaking, marketing, or content creation align with their strengths, as these roles let them share compelling stories that resonate deeply. Loreweavers thrive in environments where creativity and communication are valued, using their talent to inform, persuade, and entertain. Their ability to weave meaning into their work makes them impactful and memorable.",
        Firestarter: "The Firestarter is a dynamic personality driven by the desire to ignite change and inspire action. They thrive on bringing bold ideas to life and motivating others to push boundaries and explore new possibilities. Firestarters often excel in roles that require vision, leadership, and energy, such as entrepreneurship, activism, coaching, or innovation-focused professions. They are at their best when spearheading initiatives, rallying teams, and turning challenges into opportunities for growth and transformation. Their enthusiasm is contagious, making them natural catalysts for progress.",
        Visionweaver: "The Visionweaver is a forward-thinking personality, inspired by the possibility of creating meaningful, long-term change. They excel at imagining what could be and aligning efforts toward big-picture goals. Visionweavers often shine in roles like strategic leadership, innovation, design, or any profession that requires creative foresight and long-term planning. They are driven by purpose and thrive when they can turn abstract concepts into reality. With their ability to see connections others might miss, Visionweavers inspire those around them to believe in and work toward a shared future.",
        Truthseeker: "The Truthseeker is deeply driven by a need to uncover clarity, accuracy, and understanding. They thrive on exploring complex problems, analyzing patterns, and seeking answers that bring deeper insight to the world around them. Truthseekers are naturally drawn to careers in research, data analysis, investigative journalism, or philosophy—roles where their analytical mindset and love for knowledge can shine. They are most fulfilled when they can unravel mysteries, solve challenging questions, or contribute to meaningful, fact-driven progress.",
        Bridgekeeper: "The Bridgekeeper thrives on building strong, supportive relationships and creating a sense of unity within groups. They excel in roles that involve fostering collaboration, communication, and cooperation, such as project management, team leadership, or human resources. The Bridgekeeper is at their best when helping others understand each other, facilitating group discussions, and ensuring everyone feels heard and valued. They are often the glue that holds teams together, ensuring harmony and alignment toward shared goals. Their natural talent for connecting people makes them invaluable in any collaborative setting.",
        Soulmender: "The Soulmender is deeply attuned to the emotions and well-being of others, finding purpose in fostering understanding, healing, and connection. People with this archetype are natural caregivers, excelling in roles that require empathy, active listening, and nurturing relationships. Careers in counseling, social work, healthcare, education, or community outreach often resonate with Soulmenders, as these paths allow them to make meaningful differences in people's lives. They thrive in environments where compassion is valued and where their efforts contribute to the personal growth or emotional health of others.",
        Blacksmith: "The Blacksmith thrives on hands-on, practical work that requires skill and precision. They enjoy solving tangible problems, often in fields like construction, mechanics, or craftsmanship. Blacksmiths are fulfilled by the physical process of creating, repairing, or improving things, and they take pride in seeing the immediate results of their efforts. Careers that involve working directly with tools, machinery, or physical materials, such as electricians, plumbers, or builders, are ideal for them, as they bring together craftsmanship and problem-solving in the real world."
    },
    "metaDescription": "Does this description suit you? If so, you may want to think about in what ways your career is in line with your personality and in what ways in can be more relevant. If this description doesn’t suit you, then feel free to take a look at the other personalities so that you can find a better match and potentially learn more about yourself!",

}